# documentation: https://github.com/deltachat/sysadmin/tree/master/download.delta.chat
name: build

on: 
  push

jobs:
  upload-preview:
    runs-on: windows-latest
    name: Upload Preview
    steps:
    # Preperation
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    # Building JS
    - name: npm install, build, test
      run: |
        npm install
        npm run build
        set publish=never
        npm exec -- electron-builder --arm64 --win --config.artifactName="deltachat-desktop-win-arm64.exe"
    - name: WINDOWS renaming / upload Preperation
      if: runner.os == 'Windows'
      run: |
        cd dist
        dir
        mkdir preview
        move deltachat-desktop.exe preview/deltachat-desktop.exe
        dir preview
        cd ..
    # Upload Step
    - name: Upload result to artifacts
      uses: actions/upload-artifact@master
      with:
        name: windows
        path: dist/preview/
